services:
  app:
    build: .
    ports:
      - "3000:5000"
    volumes:
        - /private/tmp/test.db:/private/tmp/test.db
    environment:
      EMAIL: "email here"
      PASSWORD: "app password"
      SQLITE_DB_PATH: "sqlite:////private/tmp/test.db"

  redis:
    image: redis
    command: "redis-server"
    ports:
     - "6379:6379"

  rabbitmq_broker:
    image: rabbitmq
    hostname: rabbitmq_broker
    ports: 
      - "5672:5672"

  celery_worker:
      build: .
      command: celery -A Event_Scheduler worker --loglevel=info
      volumes:
        - /private/tmp/test.db:/private/tmp/test.db
      depends_on:
        - rabbitmq_broker
      environment:
        EMAIL: "email here"
        PASSWORD: "app password here"
        SQLITE_DB_PATH: "sqlite:////private/tmp/test.db"


  celery_beat:
    build: .
    command: celery -A Event_Scheduler beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    depends_on:
      - rabbitmq_broker
    environment:
      EMAIL: "email here"
      PASSWORD: "app password here"